input.onButtonPressed(Button.A, function () {
    basic.showString("20")
    basic.showString("19")
    basic.showString("18")
    basic.showString("17")
    basic.showString("16")
    basic.showString("15")
    basic.showString("14")
    basic.showString("13")
    basic.showString("12")
    basic.showString("11")
    basic.showString("10")
    basic.showString("9")
    basic.showString("8")
    basic.showString("7")
    basic.showString("6")
    basic.showString("5")
    basic.showString("4")
    basic.showString("3")
    basic.showString("2")
    basic.showString("1")
    music.setVolume(1000)
    music.startMelody(music.builtInMelody(Melodies.PowerDown), MelodyOptions.Once)
    for (let index = 0; index < 8; index++) {
        basic.showIcon(IconNames.Square)
        basic.showIcon(IconNames.SmallDiamond)
    }
})
